core/urls.py
from django.urls import path
from core.views import (HomeView,FollowDoneView, PostLikeView, PostUnlikeView,UnfollowDoneView,PostCreateView, PostDeleteView,PostDetailView, PostCommentView,PostSaveView,PostUnsaveView,LikedPostsView,SavedPostsView,ExplorePostsView,FollowRequestView,UnfollowRequestView,FollowAcceptedView,FollowersView, FollowingView)
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('feed/', login_required(HomeView.as_view()), name='home_feed_view'),
    path('follow/done',login_required(FollowDoneView.as_view()),name='follow_done_view'),
    path('follow/accepted',login_required(FollowAcceptedView.as_view()),name='follow_accepted_view'),
    path('follow/request',login_required(FollowRequestView.as_view()),name='follow_request_view'),
    path('unfollow/done',login_required(UnfollowDoneView.as_view()),name='unfollow_done_view'),
    path('unfollow/request',login_required(UnfollowRequestView.as_view()),name='unfollow_request_view'),

    path('followers/<str:username>',login_required(FollowersView.as_view()),name='followers_view'),
    path('following/<str:username>',login_required(FollowingView.as_view()),name='following_view'),

    path('post/<int:id>', login_required(PostDetailView.as_view()),name='post_detail_view'),
    path('post/create/', login_required(PostCreateView.as_view()), name='post_create_view'),
    path('post/save/<int:id>/', login_required(PostSaveView.as_view()), name='post_save_view'),
    path('post/unsave/<int:id>/', login_required(PostUnsaveView.as_view()), name='post_unsave_view'),
    path('post/delete/<int:id>',login_required(PostDeleteView.as_view()), name= 'post_delete_view'),

    path('post/liked/', login_required(LikedPostsView.as_view()), name='liked_posts_view'),
    path('post/saved/', login_required(SavedPostsView.as_view()), name='saved_posts_view'),
    path('post/explore/', login_required(ExplorePostsView.as_view()), name='explore_posts_view'),

    path('post/like/<int:id>', login_required(PostLikeView.as_view()), name='post_like_view'),
    path('post/unlike/<int:id>', login_required(PostUnlikeView.as_view()), name='post_unlike_view'),
    path('post/comment/<int:id>', login_required(PostCommentView.as_view()), name='post_comment_view')
]

insta_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('',include('core.urls')),
    path('',include('user.urls')),
    path('',include('direct.urls')),
    path('',include('notifications.urls')),
]
urlpatterns.extend(
    static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
)
# sumane !!!

notifications/urls.py
from django.urls import path
from notifications.views import NotificationView,DeleteNotificationView
from django.contrib.auth.decorators import login_required
urlpatterns = [
   	path('notifications/', login_required(NotificationView.as_view()), name='notification_view'),
   	path('<noti_id>/delete', login_required(DeleteNotificationView.as_view()), name='delete_notification_view'),
]

core/models.py
from django.db.models.deletion import CASCADE
from user.admin import User
from django.db import models
from django.contrib.auth import get_user_model
from core.utils import auto_save_current_user
from django.db.models.signals import post_save, post_delete
from notifications.models import Notification

#from crum import get_current_user
# Create your models here.
User = get_user_model()

#posts model
class Post(models.Model):
    #id =models.Autofield(primary_key=True) generated automatically
    text = models.CharField(max_length = 140, blank=True, null=True)
    image = models.ImageField(upload_to = 'post_images')    #BASE_DIR -> media ->post_images
    user = models.ForeignKey(User,on_delete = models.PROTECT, editable= False) #user_id_id
    created_on = models.DateTimeField(auto_now_add= True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering =['-created_on']
        
    def __str__(self):
        return str(self.pk)
    
    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Post, self).save(*args, **kwargs)

    @property
    def likes_count(self):
        count = self.like_set.count()
        return count

    @property
    def comments_count(self):
        count = self.comment_set.count()
        return count

#comment model
class Comment(models.Model):
    text = models.CharField(max_length = 240)
    post = models.ForeignKey(Post, on_delete =models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE,editable= False)
    commented_on = models.DateTimeField(auto_now_add = True)
    updated_on = models.DateTimeField(auto_now = True)

    def __str__(self):
        return str(self.text)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Comment, self).save(*args, **kwargs)

    def user_comment_post(sender, instance, *args, **kwargs):
        comment = instance
        post = comment.post
        text_preview = comment.text[:90]
        sender = comment.user
        notify = Notification(post=post, sender=sender, user=post.user, text_preview=text_preview ,notification_type=2)
        notify.save()

    def user_del_comment_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.user
        
        notify = Notification.objects.filter(post=post, sender=sender, notification_type=2)
        notify.delete()

#likes model
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete =models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE, editable= False)
    #is_like = models.BooleanField(default=True)
    liked_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.post.id)
    
    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Like, self).save(*args, **kwargs)

    def user_liked_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.user
        notify = Notification(post=post, sender=sender, user=post.user, notification_type=1)
        notify.save()
    
    def user_unlike_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.user
        notify = Notification.objects.filter(post=post, sender=sender, notification_type=1)
        notify.delete()

#followers model
class Follow(models.Model):
    user = models.ForeignKey(User,related_name= 'follow_follower',on_delete=models.CASCADE, editable= False)
    followed = models.ForeignKey(User,related_name= 'follow_followed',on_delete=models.CASCADE)
    followed_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    
    def __str__(self):
        return f"{self.user} --> {self.followed}"

    # def save(self, *args, **kwargs):
    #     print("inside save")
    #     print(self.user)
    #     print(self.followed)
    #     auto_save_current_user(self)
    #     super(Follow, self).save(*args, **kwargs)

    def user_follow(sender, instance, *args, **kwargs):
        follow = instance
        sender = follow.user
        following = follow.followed
        notify = Notification(sender=sender, user=following, notification_type=3)
        notify.save()
        
    def user_unfollow(sender, instance, *args, **kwargs):
	    follow = instance
	    sender = follow.user
	    following = follow.followed
	    notify = Notification.objects.filter(sender=sender, user=following, notification_type=3)
	    notify.delete()

class Request(models.Model):
    user = models.ForeignKey(User,related_name= 'request_follower',on_delete=models.CASCADE, editable= False)
    request_user = models.ForeignKey(User,related_name= 'request_followed',on_delete=models.CASCADE)
    requested_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} --> {self.request_user}"

    # def save(self, *args, **kwargs):
    #     auto_save_current_user(self)
    #     super(Request, self).save(*args, **kwargs)

    def user_request(sender, instance, *args, **kwargs):
        request = instance
        sender = request.user
        requesting = request.request_user
        notify = Notification(sender=sender, user=requesting, notification_type=4)
        notify.save()
        
    def user_unrequest(sender, instance, *args, **kwargs):
        request = instance
        sender = request.user
        requesting = request.request_user
        notify = Notification.objects.filter(sender=sender, user=requesting, notification_type=4)
        notify.delete()

class SavedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    saved_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post.pk)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(SavedPost, self).save(*args, **kwargs)


post_save.connect(Like.user_liked_post, sender=Like)
post_delete.connect(Like.user_unlike_post, sender=Like)

post_save.connect(Follow.user_follow, sender=Follow)
post_delete.connect(Follow.user_unfollow, sender=Follow)

post_save.connect(Request.user_request, sender=Request)
post_delete.connect(Request.user_unrequest, sender=Request)

post_save.connect(Comment.user_comment_post, sender=Comment)
post_delete.connect(Comment.user_del_comment_post, sender=Comment)

notifications/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Notification(models.Model):
	NOTIFICATION_TYPES = ((1,'Like'),(2,'Comment'), (3,'Follow'),(4,'Request'))

	post = models.ForeignKey('core.Post', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_from_user")
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_to_user")
	notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
	text_preview = models.CharField(max_length=90, blank=True)
	date = models.DateTimeField(auto_now_add=True)
	is_seen = models.BooleanField(default=False)

core/forms.py
from django import forms
from django.forms import fields, models, widgets
from core.models import Post
class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text','image')
        widgets = {
            'text' : forms.Textarea(attrs={
                'class': 'form-control form-control-sm',
                'placeholder': 'Caption this......',
                'id': 'captionarea'

            })
        }

notifications/views.py
from django.http.response import HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import TemplateView, View
from notifications.models import Notification
from core.models import Post
# Create your views here.
class NotificationView(View):
    template_name = "core/notification.html"

    def get(self, request, *args, **kwargs):
        user = request.user
        notifications = Notification.objects.filter(user=user).order_by('-date')
        Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)
        
        post_obj =Post.objects.filter(user=user)
        
        context = { 'notifications': notifications,'post_obj':post_obj}
        return render(request,self.template_name, context=context)

class DeleteNotificationView(View): 

    def get(self, request, *args, **kwargs):
        user = request.user
        noti_id = kwargs.get("noti_id")
        Notification.objects.filter(id=noti_id, user=user).delete()
        return redirect('notification_view')

def CountNotifications(request):
	count_notifications = 0
	if request.user.is_authenticated:
		count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()

	return {'count_notifications':count_notifications}

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'styles/core/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/core/navbar.css' %}">
    {% block extra_head %}{% endblock %}

    <title>Insta Clone</title>
  </head>
  <body style="background-color: #fafafa;">

    {% include 'components/navbar.html' %}

    <section>
      {% block content %}{% endblock %}
    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

  </body>
</html>

templates/core/feed.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/core/post_card.css' %}">
<script src="https://cdn.tiny.cloud/1/9p117lktpcqi40ynvqmggnqoi8mj4glno653bigcf5k4rvcc/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
	tinymce.init({
	  selector: "#captionarea",
	  plugins: "emoticons",
	  toolbar: "emoticons",
	  toolbar_location: "top-left",
	  menubar: false,
	  forced_root_block : false,
	  width: "470",
	  height: "110"
	});
</script>
{% endblock %}

{% block content %}

    <!-- Messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success w-50 mt-4 mx-auto text-center {{ message.tags }}" role="alert" style="font-size: 13px;">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12 col-md-8">
                <div class="card mx-auto mb-4" style="max-width: 32rem;">
                    <div class="card-body">
                        <div>

                            <!-- Post Create Form -->
                            <form method="POST" action="{% url 'post_create_view' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="mb-2">{{ field }}</div>
                                {% endfor %}
                                <button class="btn btn-sm btn-primary" type="submit">Save</button>
                            </form>
                            <!-- Post Create Form End -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8">

                <!-- All the posts in database -->
                {% for post in all_posts %}

                    <!-- Single Posts Card -->
                    {% include 'components/post_card.html' %}
                    
                {% endfor %}
                <!-- All the posts in database -->

            </div>
        </div>
    </div>
{% endblock %}

templates/core/liked_posts.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All Liked Posts -->
            {% for like_obj in request.user.like_set.all %}
                {% with post=like_obj.post %}

                <!-- Single Posts Grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post Image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">

                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- total comments -->
                                {{ post.comments_count }}
                                
                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single Posts Grid end -->

                {% endwith %}
            {% endfor %}
            <!-- All Liked Posts end -->

        </div>
    </div>

{% endblock %}

templates/core/notification.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/user/all_profiles.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-12 col-md-5 card offset-md-3">
            {% if notifications %}    
                {% for notification in notifications %}
                    {% if notification.notification_type == 2 %}        
                            <div class="row py-3 px-5 border-bottom">                                    
                                    <figure class="media-left">
                                        <p class="image is-64x64">
                                            {% if notification.sender.picture %}
                                                <img src="/media/{{ notification.sender.picture }}" class="rounded-circle z-depth-0 profile__pic">
                                            {% else %}
                                                <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                                            {% endif %}
                                        </p>
                                    </figure>
                                    
                                    <div class="media-content">
                                        <div class="content mx-2">
                                            <a href="{% url 'profile_view' notification.sender.username %}">
                                                <strong>{{ notification.sender.full_name }} </strong> <small>@{{ notification.sender.username }}</small> 
                                            </a>
                                            <p><span class="fas fa-comment-dots"></span> Commented on</p>
                                            <p>{{ notification.text_preview }}</p>
                                            <strong><small>{{ notification.date|naturaltime }}</small></strong>
                                        </div>
                                    </div>

                                    <div class="ml-auto">                            
                                        <a href="{% url 'post_detail_view' notification.post %}">
                                            {% if notification.sender.picture %}
                                                <img src="{{ notification.post.image.url }}" height="80" width="80" >
                                            {% else %}
                                                <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                                            {% endif %}                                            
                                        </a>                                       
                                    </div>
                                    <a href="{% url 'delete_notification_view' notification.id %}" class="content mx-2"><i class="fas fa-times-circle" style="color: black;"></i></a>
                            </div>
                    {% endif %}
                    {% if notification.notification_type == 3 %}
                        <div class="row py-3 px-5 border-bottom">                                    
                            <figure class="media-left">
                                <p class="image is-64x64">
                                    {% if notification.sender.picture %}
                                        <img src="/media/{{ notification.sender.picture }}" class="rounded-circle z-depth-0 profile__pic">
                                    {% else %}
                                        <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                                    {% endif %}
                                </p>
                            </figure>
                            <div class="media-content">
                                <div class="content mx-2">
                                    <a href="{% url 'profile_view' notification.sender.username %}">
                                        <strong>{{ notification.sender.full_name }} </strong> <small>@{{ notification.sender.username }}</small> 
                                    </a>
                                    
                                    <p><i class="fas fa-user"></i> Followed You</p>
                                    <strong><small>{{ notification.date|naturaltime }}</small></strong>
                                </div>
                            </div>
                            <div class="ml-auto">                                                                                                                
                                <a href="{% url 'delete_notification_view' notification.id %}" class="content mx-2"><i class="fas fa-times-circle" style="color: black;"></i></a>
                                
                            </div>
                        </div>
                    {% endif %}
                    {% if notification.notification_type == 4 %}
                        <div class="row py-3 px-5 border-bottom">                                    
                            <figure class="media-left">
                                <p class="image is-64x64">
                                    {% if notification.sender.picture %}
                                        <img src="/media/{{ notification.sender.picture }}" class="rounded-circle z-depth-0 profile__pic">
                                    {% else %}
                                        <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                                    {% endif %}
                                </p>
                            </figure>
                            <div class="media-content">
                                <div class="content mx-2">
                                    <a href="{% url 'profile_view' notification.sender.username %}">
                                        <strong>{{ notification.sender.full_name }} </strong> <small>@{{ notification.sender.username }}</small> 
                                    </a>
                                    <p><i class="fas fa-user"></i> Requested to follow you</p>
                                    <strong><small>{{ notification.date|naturaltime }}</small></strong>
                                </div>
                            </div>
                            <div class="ml-auto">                                                                                                                            
                                <a href="{% url 'delete_notification_view' notification.id %}" class="content mx-2"><i class="fas fa-times-circle" style="color: black;"></i></a>                                                    
                            </div>
                            <div class="form-inline">
                                <form method="POST" action="{% url 'follow_accepted_view' %}">
                                    {% csrf_token %}
                                    <input type="number" name="accepted_user_id" hidden value="{{ notification.sender.pk }}">
                                    <button class="px-2 btn btn-sm btn-primary mx-2" type="submit">Accept Follow Request</button>
                                </form>
                                <form method="POST" action="{% url 'unfollow_request_view' %}">
                                    {% csrf_token %}
                                    <input type="number" name="unrequest_user_id" hidden value="{{ notification.sender.pk }}">
                                    <button class="px-2 btn btn-sm btn-success mx-2" type="submit">Cancel Follow Request</button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                    {% if notification.notification_type == 1 %}        
                            <div class="row py-3 px-5 border-bottom">                                    
                                    <figure class="media-left">                                    
                                        <p class="image is-64x64">
                                            {% if notification.sender.picture %}
                                                <img src="/media/{{ notification.sender.picture }}" class="rounded-circle z-depth-0 profile__pic">
                                            {% else %}
                                                <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                                            {% endif %}
                                        </p>
                                    </figure>
                                    
                                    <div class="media-content">
                                        <div class="content mx-2">
                                            <a href="{% url 'profile_view' notification.sender.username %}">
                                                <strong>{{ notification.sender.full_name }} </strong> <small>@{{ notification.sender.username }}</small> 
                                            </a>
                                            <p><i class="fas fa-thumbs-up"></i> Liked your post</p>
                                            <p>{{ notification.text_preview }}</p>
                                            <strong><small>{{ notification.date|naturaltime }}</small></strong>
                                        </div>
                                    </div>

                                    <div class="ml-auto"> 
                                        <a href="{% url 'post_detail_view' notification.post %}">
                                            {% if notification.sender.picture %}
                                                <img src="{{ notification.post.image.url }}" height="80" width="80" >
                                            {% else %}
                                                <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                                            {% endif %}                                            
                                        </a>
                                    </div>
                                    <a href="{% url 'delete_notification_view' notification.id %}" class="content mx-2"><i class="fas fa-times-circle" style="color: black;"></i></a>
                            </div>
                    {% endif %}
                {% endfor %}                 
            {% else %}
                <p class="justify-content-center text-center mx-auto my-5">No Notifications to display</p>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/post_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/core/post_card.css' %}">
{% endblock %}

{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12">

                <!-- Single Posts in Detail Card -->
                {% include 'components/post_detail_card.html' %}
                
            </div>
        </div>
    </div>

{% endblock %}

templates/core/saved_posts.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All Saved Posts -->
            {% for savedpost_obj in request.user.savedpost_set.all %}
                {% with post=savedpost_obj.post %}

                <!-- Single Posts Grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">
                        
                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- Total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- Total comments -->
                                {{ post.comments_count }}

                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single Posts Grid end -->

                {% endwith %}
            {% endfor %}
            <!-- All Saved Posts end -->

        </div>
    </div>

{% endblock %}